### ISSUE TITLE
PixelmonGO Tweak Suggestion 

### ISSUE THREAD

**Issue by DILLOY** [MrWhiteFlamesYT/ZeroG-Pixelmon-Obsidian-Edition#11]
**Description**

**Could you write a short description of your suggestion here?**
Ok something I have noticed right off the bat is that the pixelmon go mod should be tweaked a bit to make it rare to obtain legendaries, some of the item pools for the poke stops should be tweaked enough where it going to be used to get pixelmon eggs a lot less and more rare to get higher tier eggs.

**Why would you like this added/changed?**
It's just an overall QoL edit that would make getting legendaries and rare items feel more rewarding.

**Screenshots if applicable.**
no screenshot.

**Comment by MrWhiteFlamesYT-dev** [comment]
Removing mod in next update, and improving pixelmon poke stop frequency to spawn more and added a mod to do poke eggs and trading.
