### ISSUE TITLE
PokeballReveal MOD

### ISSUE THREAD

**Issue by DILLOY** [MrWhiteFlamesYT/ZeroG-Pixelmon-Obsidian-Edition#12]
**CurseForge Link**
https://legacy.curseforge.com/minecraft/mc-mods/pokeballreveal

**Mod description**
This mod adds Pixelmon’s Pokeballs to JEI to allow for looking up recipes. Normally the recipes is not shown in JEI, at all times, but this mod changes that.

**Why would you like the mod added?*
QoL mod that a lot of new players would really benefit from them not knowing how to craft Pokeballs

**Screenshots if applicable.**

https://imgur.com/a/gv2w2UB

**Comment by MrWhiteFlamesYT-dev** [comment]
The mod has been added to [Version 1.7.12b](https://github.com/ZeroG-Network/ZeroG-Pixelmon-Obsidian-Edition/blob/1.16.5/Changelogs/Changelog-Changelogs/v1.1.7.12b-Changelog_Changes.md) of the pack.
