### ISSUE TITLE
PixelMagics MOD

### ISSUE THREAD

**Issue by DILLOY** [MrWhiteFlamesYT/ZeroG-Pixelmon-Obsidian-Edition#13]
**CurseForge Link**

https://www.curseforge.com/minecraft/mc-mods/pixelmagics

**Mod description**

PixelMagics is a QOL Mod for Pixelmon Reforged 9.1.6 that adds Coupons to edit your Pokemon, Fishing points to enter the drowned world, Flutes to summon Pokemon, awake statues, Eggs from poke stops, Personality Quiz to get your Partner Pokemon (Mystery Dungeon style) and more.

**Why would you like the mod added?**

It's a QOL addon mod for pixelmon that has its own toggable modules, Moist and I were talking about it and we came to the conclusion that some of these modules could be deemed useful to admins and general players, the module that stood out to me and moist specify was **Breed-Switch** which you can see below.

These are considered coupon items.. the Following 'Coupon-Items' are part of the Base Module

Sparkler -> Toggle Shiny/Non Shiny of your Pokemon
Shrinker -> Decrease the Size
Inflater -> Increase the Size
IV-Dice -> Re-roll all IV's (random)
IV-Max -> Maximise one IV (random, can hit same stat, so its not that OP)
Sex-Switch -> Toggle Male/Female Gender (Cannot be used on Genderless Pixelmons)
**Ball-Switch -> Switch the Pokeball of your Pokemon with the Ball in your First Inventory Slot (Want your Legendary in a Nest Ball and get your Master Ball back?!)**
Rebirth -> Transform your Pokemon back to Level 1, Reset EV's and Randomise Nature 
Breed-Switch -> Make your Pokemon Unbreedable/Breedable. (Only Works if the Pokemon originally was from you OT)
Skin-AR -> Change the Skin of your Pokemon, if it has atleast one. If it has more then one you can toggle between them. (works on Custom Skins too!)
Random Coupon -> Shift + Rightclick to Obtain a Random Coupon (except Skin-AR)

Ball-Switch is bold due to it being overpowered.    (pretty sure we can turn off or remove the features/modules) 

**Screenshots if applicable.**

**Comment by MrWhiteFlamesYT-dev** [comment]
Mod has been added to dev pack to see if it works and to be configured.

**Comment by MrWhiteFlamesYT-dev** [comment]
Will be the new mod to be replaced with the pixelmongo mod.

[Issue #11](https://github.com/ZeroG-Network/ZeroG-Pixelmon-Obsidian-Edition/issues/11) has been closed for this mod.

**Comment by MrWhiteFlamesYT-dev** [comment]
[Version 1.7.12b](https://github.com/ZeroG-Network/ZeroG-Pixelmon-Obsidian-Edition/blob/1.16.5/Changelogs/Changelog-Changelogs/v1.1.7.12b-Changelog_Changes.md) got this mod in.
