### ISSUE TITLE
Forestry MOD Bug 

### ISSUE THREAD

**Issue by DILLOY** [MrWhiteFlamesYT/ZeroG-Pixelmon-Obsidian-Edition#14]
**Modpack version**
ZeroG-Pixelmon-Obsidian-Edition latest dev
**Describe the bug**
I was scrolling through mods and found a bunch of purple and black squares 
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
none
**Screenshots**
https://www.youtube.com/watch?v=dF2ZApfEpSw

**Comment by MrWhiteFlamesYT-dev** [comment]
This is an issue with the mod not the pack not much we can do on the fixture of this items, mod has temporarily been removed from the pack till further notice.
