### ISSUE TITLE
AquaGTS MOD

### ISSUE THREAD

**Issue by DILLOY** [MrWhiteFlamesYT/ZeroG-Pixelmon-Obsidian-Edition#15]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/gts

**Mod description**
Write a short description of the mod here.
AquaGTS includes all three of a Global Trade System, for selling or trading of items and Pokémon, an Auction House, for running auctions of items and Pokémon, and a Sell to Server, for getting rid of items and Pokémon immediately for money.

**Why would you like the mod added?**
I think it would be pretty cool when the big public server release happens plus its very customizable
**Screenshots if applicable.**

**Comment by ZeroG-Network** [comment]
This mod not going to be used anymore since Pack v1.2.1
